#!/usr/bin/env bash
# make-case.sh — generate the test/benchmark simulation, using ONLY data that
# ships inside GROMACS itself.
#
# Why generate rather than download: the usual GROMACS benchmarks (benchMEM,
# ADH, the regressiontests tarball) are external downloads, which makes the test
# depend on a third-party host being up and on the compute nodes having outbound
# network. Everything here comes from $GMXDATA/top, which every GROMACS install
# already contains:
#   spc216.gro              a 216-molecule equilibrated SPC water box
#   oplsaa.ff/spce.itp      the SPC/E water topology
# `gmx solvate` replicates spc216 to fill a box of any size and writes the
# molecule count into the topology, so one command gives a system of any size.
#
# The result is a plain PME + LINCS water box: unremarkable physics, but it
# exercises exactly the code paths that decide GROMACS performance and
# correctness on this machine — the SIMD non-bonded kernels (the SVE-vs-NEON
# question), the FFT library (cray-fftw vs from-source fftw) and, once run on
# more than one node, the MPI halo exchange and PME grid transposes.
#
# Usage:  bash tests/make-case.sh <outdir> [box_nm] [nsteps]
# Needs the thread-MPI `gmx` on PATH (module load gromacs-env/...).
set -euo pipefail

outdir="${1:?usage: make-case.sh <outdir> [box_nm] [nsteps]}"
box="${2:-12.0}"        # 12 nm cube -> ~57k SPC/E molecules -> ~172k atoms
nsteps="${3:-20000}"    # 20000 * 2 fs = 40 ps

command -v gmx >/dev/null 2>&1 || {
  echo "ERROR: gmx (thread-MPI) not on PATH — module load gromacs-env/<version>/<variant>" >&2
  exit 1
}

mkdir -p "$outdir"
cd "$outdir"

# --- Topology --------------------------------------------------------------
# `gmx solvate -p` appends the actual SOL count to [ molecules ], so we only
# have to name the force field and the water model.
cat > topol.top <<'TOP'
; Generated by tests/make-case.sh — SPC/E water box, OPLS-AA parameters.
#include "oplsaa.ff/forcefield.itp"
#include "oplsaa.ff/spce.itp"

[ system ]
SPC/E water box

[ molecules ]
TOP

# --- Run parameters --------------------------------------------------------
# Chosen to be representative of a production biomolecular MD run rather than to
# flatter any particular build:
#   PME with a 0.12 nm grid    the FFT + MPI-collective-heavy part
#   verlet cutoffs at 1.0 nm   the SIMD non-bonded kernel part
#   nstlist 40                 GROMACS re-tunes this at runtime anyway
#   h-bond constraints, 2 fs   standard production timestep
#   nstcalcenergy 100          energies are needed for the correctness check,
#                              but computing them every step would distort the
#                              performance measurement
cat > grompp.mdp <<MDP
integrator               = md
dt                       = 0.002
nsteps                   = $nsteps
; --- output: nothing. Trajectory IO would benchmark the filesystem, not GROMACS.
nstxout                  = 0
nstvout                  = 0
nstfout                  = 0
nstlog                   = 1000
nstenergy                = 1000
nstcalcenergy            = 100
; --- neighbour searching / cutoffs
cutoff-scheme            = Verlet
nstlist                  = 40
rlist                    = 1.0
coulombtype              = PME
rcoulomb                 = 1.0
fourierspacing           = 0.12
pme-order                = 4
vdwtype                  = cutoff
rvdw                     = 1.0
DispCorr                 = EnerPres
; --- constraints
constraints              = h-bonds
constraint-algorithm     = lincs
; --- ensemble: NVT with a deterministic starting state, so every build and
;     every node count starts from bit-identical initial conditions and the
;     correctness comparison across builds is meaningful.
tcoupl                   = v-rescale
tc-grps                  = System
tau-t                    = 0.5
ref-t                    = 300
ld-seed                  = 42
gen-vel                  = yes
gen-temp                 = 300
gen-seed                 = 42
MDP

echo "== Solvating a ${box} nm cube from GROMACS' bundled spc216.gro"
gmx solvate -cs spc216.gro -box "$box" "$box" "$box" -o conf.gro -p topol.top

echo "== grompp"
gmx grompp -f grompp.mdp -c conf.gro -p topol.top -o bench.tpr -maxwarn 1

# Atom count straight from the .gro header (line 2 is the atom count, by format).
# Deliberately NOT `gmx dump -s bench.tpr | grep -m1 natoms`: under `set -o
# pipefail` that reports failure even on success, because `grep -m1` exits after
# the first match and `gmx dump` then dies of SIGPIPE. Reading the file cannot
# fail, and needs no second GROMACS invocation.
natoms="$(sed -n '2p' conf.gro | tr -dc '0-9')"
echo "CASE_OK  tpr=$PWD/bench.tpr  atoms=${natoms:-?}  nsteps=$nsteps"
